#!/bin/bash

prog=$(./gradlew --console=plain run --args="$1" 2>&1 >/dev/null | grep "non-zero exit value")



if echo $prog | grep -q "100"; then
    exit 100
elif echo $prog | grep -q "200"; then
    exit 200
else
    exit 0
fi